In [3]:
from math import sqrt

import numpy as np

In [1]:
def rodriges(dir, angulo):
    cosang = np.cos(angulo)
    r = cosang * np.eye(3)
    r += (1-cosang)*(dir * dir.T)
    sk = np.array([[0, -dir[2], dir[1]],
                   [dir[2], 0, -dir[0]],
                   [-dir[1], dir[0], 0]])
    r += np.sin(angulo) * sk
    return r

In [5]:
R = rodriges(np.array([0.57735, 0.57735, 0.57735]),np.pi*25/180)

print(R)

[[ 0.9375385  -0.21276794  0.27522936]
 [ 0.27522936  0.9375385  -0.21276794]
 [-0.21276794  0.27522936  0.9375385 ]]


In [10]:
dir = np.array([2,1,1])
norm = np.sqrt(dir @ dir.T)
R = rodriges((1/norm)*dir,np.pi*(-22)/180)

erre = np.array([4,6,0])
p = np.array([6,12,-3])

print(R @ erre + p)

[10.89332296 17.21836566 -3.95646748]


In [12]:
dir = np.array([1,-1,4]
norm = np.sqrt(dir @ dir.T)
R = rodriges((1/norm)*dir,np.pi*15/180)

erre = np.array([10,5,15])
p = np.array([5,-15,2])

print(R @ erre + p)

SyntaxError: '(' was never closed (3486881154.py, line 1)