In [2]:
from math import sqrt

import numpy as np

In [3]:
def rodriges(dir, angulo):
    cosang = np.cos(angulo)
    r = cosang * np.eye(3)
    r += (1-cosang)*(dir * dir.T)
    sk = np.array([[0, -dir[2], dir[1]],
                   [dir[2], 0, -dir[0]],
                   [-dir[1], dir[0], 0]])
    r += np.sin(angulo) * sk
    return r

In [4]:
R = rodriges(np.array([0.57735, 0.57735, 0.57735]),np.pi*25/180)

print(R)

[[ 0.9375385  -0.21276794  0.27522936]
 [ 0.27522936  0.9375385  -0.21276794]
 [-0.21276794  0.27522936  0.9375385 ]]


In [5]:
dir = np.array([2,1,1])
norm = np.sqrt(dir @ dir.T)
R = rodriges((1/norm)*dir,np.pi*(-22)/180)

erre = np.array([4,6,0])
p = np.array([6,12,-3])

print(R @ erre + p)

[10.89332296 17.21836566 -3.95646748]


In [11]:
dir3 = np.array([1,-1,0])
dir2 = np.array([0,1,1])
norm3 = np.sqrt(dir3 @ dir3.T)
norm2 = np.sqrt(dir2 @ dir2.T)
R2 = rodriges((1/norm2)*dir2,np.pi*12/180)
R3 = rodriges((1/norm3)*dir3,np.pi*(-20)/180)

erre = np.array([10,5,15])
p12 = np.array([3,4,5])
p23 = np.array([0,-2,-1])



print(-R3 @ p23 -R3 @ R2 @ p12)

[-4.01591951 -3.33199161 -2.14185934]
